// Default restaurant data for seeding new lists
export interface DefaultRestaurant {
  name: string;
  location: string;
  cuisine: string;
  visited: boolean;
  rating: number;
}

const defaults: DefaultRestaurant[] = [
  // Italiano
  { name: "Bosco", location: "Pinheiros, São Paulo", cuisine: "Italiano", visited: false, rating: 0 },
  { name: "Enoteca Saintvinsaint", location: "São Paulo", cuisine: "Italiano", visited: false, rating: 0 },
  { name: "Fiaschetteria del Capitale", location: "São Paulo", cuisine: "Italiano", visited: false, rating: 0 },
  { name: "Vecchio Torino", location: "São Paulo", cuisine: "Italiano", visited: false, rating: 0 },
  { name: "Elea Forneria", location: "São Paulo", cuisine: "Italiano", visited: false, rating: 0 },
  { name: "Borgo Mooca", location: "Mooca, São Paulo", cuisine: "Italiano", visited: false, rating: 0 },
  { name: "Il Capitale", location: "São Paulo", cuisine: "Italiano", visited: false, rating: 0 },
  { name: "Il Carpaccio", location: "Itaim, São Paulo", cuisine: "Italiano", visited: false, rating: 0 },
  { name: "Krozta", location: "Centro, São Paulo", cuisine: "Italiano", visited: false, rating: 0 },
  { name: "La Piana", location: "Jardins, São Paulo", cuisine: "Italiano", visited: false, rating: 0 },
  { name: "Grotta", location: "Jardins, São Paulo", cuisine: "Italiano", visited: false, rating: 0 },
  { name: "Tappo", location: "São Paulo", cuisine: "Italiano", visited: false, rating: 0 },
  { name: "Picchi", location: "São Paulo", cuisine: "Italiano", visited: false, rating: 0 },
  { name: "Biccheri", location: "Pinheiros, São Paulo", cuisine: "Italiano", visited: false, rating: 0 },
  { name: "Caco", location: "São Paulo", cuisine: "Italiano", visited: false, rating: 0 },
  { name: "Cozinha dos Ferrari", location: "São Paulo", cuisine: "Italiano", visited: false, rating: 0 },
  { name: "Simone", location: "São Paulo", cuisine: "Italiano", visited: false, rating: 0 },
  { name: "Prego Único", location: "São Paulo", cuisine: "Italiano", visited: false, rating: 0 },
  { name: "Lina", location: "São Paulo", cuisine: "Italiano", visited: false, rating: 0 },
  { name: "Follia", location: "Vila Madalena, São Paulo", cuisine: "Italiano", visited: false, rating: 0 },
  { name: "Matacitta", location: "Rosewood, São Paulo", cuisine: "Italiano", visited: false, rating: 0 },
  { name: "Pour Vouz", location: "São Paulo", cuisine: "Italiano", visited: false, rating: 0 },

  // Japonês / Asiático
  { name: "Yunagi Edomae", location: "São Paulo", cuisine: "Japonês", visited: false, rating: 0 },
  { name: "Hon Maguro", location: "São Paulo", cuisine: "Japonês", visited: false, rating: 0 },
  { name: "Goya Sushi", location: "São Paulo", cuisine: "Japonês", visited: false, rating: 0 },
  { name: "Kuromoon", location: "São Paulo", cuisine: "Japonês", visited: false, rating: 0 },
  { name: "Quito Quito", location: "São Paulo", cuisine: "Japonês", visited: false, rating: 0 },
  { name: "Sushi Nami", location: "São Paulo", cuisine: "Japonês", visited: false, rating: 0 },
  { name: "Charm Nomiya", location: "São Paulo", cuisine: "Japonês", visited: false, rating: 0 },
  { name: "Oizume Sushi Omakase", location: "São Paulo", cuisine: "Japonês", visited: false, rating: 0 },
  { name: "Hidden Buns and Noodles", location: "São Paulo", cuisine: "Asiático", visited: false, rating: 0 },
  { name: "Daiki", location: "São Paulo", cuisine: "Japonês", visited: false, rating: 0 },
  { name: "Imai Izakaya", location: "São Paulo", cuisine: "Japonês", visited: false, rating: 0 },
  { name: "Izakaya Matsu", location: "São Paulo", cuisine: "Japonês", visited: false, rating: 0 },
  { name: "Tenko", location: "São Paulo", cuisine: "Japonês", visited: false, rating: 0 },
  { name: "Ruan Jia Fu", location: "São Paulo", cuisine: "Coreano", visited: false, rating: 0 },
  { name: "Nosu", location: "São Paulo", cuisine: "Japonês", visited: false, rating: 0 },
  { name: "Kinki Zushi", location: "São Paulo", cuisine: "Japonês", visited: false, rating: 0 },
  { name: "Izakaya Kabura", location: "São Paulo", cuisine: "Japonês", visited: false, rating: 0 },
  { name: "Yakiniku Yoridokoro", location: "Paraíso, São Paulo", cuisine: "Japonês", visited: false, rating: 0 },
  { name: "Standing Sushi Bar", location: "São Paulo", cuisine: "Japonês", visited: false, rating: 0 },
  { name: "Ikemen Ramen", location: "São Paulo", cuisine: "Japonês", visited: false, rating: 0 },
  { name: "Barikote Ramen", location: "São Paulo", cuisine: "Japonês", visited: false, rating: 0 },
  { name: "Bao Hut", location: "São Paulo", cuisine: "Asiático", visited: false, rating: 0 },
  { name: "Saiko Sando", location: "São Paulo", cuisine: "Japonês", visited: false, rating: 0 },
  { name: "Yubari", location: "Bela Vista, São Paulo", cuisine: "Japonês", visited: false, rating: 0 },
  { name: "Tempura Ten", location: "São Paulo", cuisine: "Japonês", visited: false, rating: 0 },
  { name: "Yoshi Izakaya", location: "São Paulo", cuisine: "Japonês", visited: false, rating: 0 },
  { name: "Jojo Ramen", location: "São Paulo", cuisine: "Japonês", visited: false, rating: 0 },
  { name: "Sho Sun Gal Bi", location: "São Paulo", cuisine: "Coreano", visited: false, rating: 0 },
  { name: "Miyabi", location: "São Paulo", cuisine: "Japonês", visited: false, rating: 0 },
  { name: "Noda 835", location: "São Paulo", cuisine: "Japonês", visited: false, rating: 0 },
  { name: "Vaz Nori", location: "São Paulo", cuisine: "Japonês", visited: false, rating: 0 },
  { name: "Kuzuri Izakaya", location: "São Paulo", cuisine: "Japonês", visited: false, rating: 0 },
  { name: "Kureiji", location: "São Paulo", cuisine: "Japonês", visited: false, rating: 0 },
  { name: "Marudai", location: "São Paulo", cuisine: "Japonês", visited: false, rating: 0 },
  { name: "Casa Aguiko", location: "São Paulo", cuisine: "Japonês", visited: false, rating: 0 },
  { name: "Lavva", location: "São Paulo", cuisine: "Coreano", visited: false, rating: 0 },
  { name: "Mokutan", location: "São Paulo", cuisine: "Japonês", visited: false, rating: 0 },
  { name: "Hi-Fi Community", location: "São Paulo", cuisine: "Asiático", visited: false, rating: 0 },

  // Frutos do Mar
  { name: "Aquiles", location: "Itaim, São Paulo", cuisine: "Frutos do Mar", visited: false, rating: 0 },
  { name: "Gal Bar do Mar", location: "Itaim, São Paulo", cuisine: "Frutos do Mar", visited: false, rating: 0 },
  { name: "Cepa", location: "Pinheiros, São Paulo", cuisine: "Frutos do Mar", visited: false, rating: 0 },
  { name: "Bill Ostras", location: "Bertioga", cuisine: "Frutos do Mar", visited: false, rating: 0 },
  { name: "Boteco Miraflores", location: "Zona Norte, São Paulo", cuisine: "Frutos do Mar", visited: false, rating: 0 },
  { name: "Tortuga", location: "São Paulo", cuisine: "Frutos do Mar", visited: false, rating: 0 },
  { name: "Mares de Lá", location: "São Paulo", cuisine: "Peruano", visited: false, rating: 0 },

  // Besteiras
  { name: "Komah Bakery", location: "São Paulo", cuisine: "Padaria", visited: false, rating: 0 },
  { name: "O Jardins", location: "Campo Belo, São Paulo", cuisine: "Brunch", visited: false, rating: 0 },
  { name: "Coliseum Panini", location: "São Paulo", cuisine: "Lanche", visited: false, rating: 0 },
  { name: "Italien Sorvete", location: "São Paulo", cuisine: "Sobremesa", visited: false, rating: 0 },
  { name: "Borger Burger", location: "São Paulo", cuisine: "Hamburgueria", visited: false, rating: 0 },
  { name: "By Kim", location: "São Paulo", cuisine: "Lanche", visited: false, rating: 0 },
  { name: "Crime", location: "São Paulo", cuisine: "Lanche", visited: false, rating: 0 },
  { name: "Mira Padaria", location: "São Paulo", cuisine: "Padaria", visited: false, rating: 0 },
  { name: "Oli Pizza", location: "São Paulo", cuisine: "Pizzaria", visited: false, rating: 0 },
  { name: "Helena di Napoli", location: "São Paulo", cuisine: "Pizzaria", visited: false, rating: 0 },
  { name: "Braz Quintal", location: "São Paulo", cuisine: "Pizzaria", visited: false, rating: 0 },
  { name: "Mimada Brunch", location: "São Paulo", cuisine: "Brunch", visited: false, rating: 0 },

  // Variado
  { name: "Talita", location: "Conceição Discos, São Paulo", cuisine: "Variado", visited: false, rating: 0 },
  { name: "Tuju", location: "São Paulo", cuisine: "Variado", visited: false, rating: 0 },
  { name: "Casa do Saulo", location: "Vila Olímpia, São Paulo", cuisine: "Paraense", visited: false, rating: 0 },
  { name: "Merenda da Cidade", location: "São Paulo", cuisine: "Variado", visited: false, rating: 0 },
  { name: "Ara", location: "São Paulo", cuisine: "Sobremesa", visited: false, rating: 0 },
  { name: "Belô", location: "São Paulo", cuisine: "Mineiro", visited: false, rating: 0 },
  { name: "Leila", location: "Tania Bulhões, São Paulo", cuisine: "Francês", visited: false, rating: 0 },
  { name: "Tantin", location: "Pinheiros, São Paulo", cuisine: "Variado", visited: false, rating: 0 },
  { name: "Paradiso", location: "Jardins, São Paulo", cuisine: "Variado", visited: false, rating: 0 },
  { name: "Taboa", location: "Vila Madalena, São Paulo", cuisine: "Variado", visited: false, rating: 0 },
  { name: "Virado", location: "Centro, São Paulo", cuisine: "Variado", visited: false, rating: 0 },
  { name: "Cepa", location: "Anália Franco, São Paulo", cuisine: "Variado", visited: false, rating: 0 },
  { name: "Parador", location: "Centro, São Paulo", cuisine: "Variado", visited: false, rating: 0 },
  { name: "Atzi Tacos", location: "Vila Madalena, São Paulo", cuisine: "Mexicano", visited: false, rating: 0 },
  { name: "Feriae", location: "São Paulo", cuisine: "Variado", visited: false, rating: 0 },
  { name: "Dalva e Dito", location: "São Paulo", cuisine: "Brasileiro", visited: false, rating: 0 },
  { name: "Hi Pin Shanm", location: "São Paulo", cuisine: "Variado", visited: false, rating: 0 },
  { name: "Casa Rios", location: "São Paulo", cuisine: "Variado", visited: false, rating: 0 },
  { name: "Cala del Tanit", location: "São Paulo", cuisine: "Variado", visited: false, rating: 0 },
  { name: "Bistrô de Paris", location: "São Paulo", cuisine: "Francês", visited: false, rating: 0 },
  { name: "Frangrill", location: "São Paulo", cuisine: "Variado", visited: false, rating: 0 },
  { name: "Sonho Árabe", location: "São Paulo", cuisine: "Árabe", visited: false, rating: 0 },
  { name: "Los Dos Cantina", location: "São Paulo", cuisine: "Mexicano", visited: false, rating: 0 },
  { name: "Shoshana", location: "São Paulo", cuisine: "Judaico", visited: false, rating: 0 },
  { name: "Mordisco", location: "São Paulo", cuisine: "Variado", visited: false, rating: 0 },
  { name: "Tenda do Nilo", location: "São Paulo", cuisine: "Árabe", visited: false, rating: 0 },
  { name: "Grindhouse", location: "São Paulo", cuisine: "Carnes", visited: false, rating: 0 },
  { name: "Fresh Goodies", location: "São Paulo", cuisine: "Saudável", visited: false, rating: 0 },
  { name: "Singelo Braseiro", location: "São Paulo", cuisine: "Variado", visited: false, rating: 0 },
  { name: "Leitaria Ita", location: "São Paulo", cuisine: "Variado", visited: false, rating: 0 },
  { name: "Lá Napoleon", location: "Jardins, São Paulo", cuisine: "Francês", visited: false, rating: 0 },
  { name: "A Libanesinha", location: "São Paulo", cuisine: "Árabe", visited: false, rating: 0 },
  { name: "Nomo", location: "Vila Madalena, São Paulo", cuisine: "Variado", visited: false, rating: 0 },
  { name: "D'Heaven SP", location: "São Paulo", cuisine: "Francês", visited: false, rating: 0 },
  { name: "Cazeco", location: "São Paulo", cuisine: "Variado", visited: false, rating: 0 },
  { name: "Lena", location: "Pinheiros, São Paulo", cuisine: "Mineiro", visited: false, rating: 0 },
  { name: "Lá Cura Gastronomia", location: "Vila Madalena, São Paulo", cuisine: "Variado", visited: false, rating: 0 },
  { name: "Josefa", location: "Vila Mariana, São Paulo", cuisine: "Variado", visited: false, rating: 0 },
  { name: "Bodega Pepito", location: "São Paulo", cuisine: "Variado", visited: false, rating: 0 },
  { name: "Cellar Cave", location: "São Paulo", cuisine: "Bar de Vinhos", visited: false, rating: 0 },
  { name: "Kez", location: "São Paulo", cuisine: "Brunch", visited: false, rating: 0 },
  { name: "Isca", location: "Pompeia, São Paulo", cuisine: "Variado", visited: false, rating: 0 },
  { name: "Sertó", location: "São Paulo", cuisine: "Brasileiro", visited: false, rating: 0 },
  { name: "Le Freak", location: "São Paulo", cuisine: "Francês", visited: false, rating: 0 },
  { name: "El Bodegon", location: "São Paulo", cuisine: "Variado", visited: false, rating: 0 },
  { name: "Tosta", location: "São Paulo", cuisine: "Variado", visited: false, rating: 0 },
  { name: "Curado", location: "São Paulo", cuisine: "Variado", visited: false, rating: 0 },
  { name: "Repiola", location: "São Paulo", cuisine: "Variado", visited: false, rating: 0 },

  // Delivery
  { name: "Ticana", location: "São Paulo", cuisine: "Delivery", visited: false, rating: 0 },
  { name: "Bar Balcão (Delivery)", location: "São Paulo", cuisine: "Delivery", visited: false, rating: 0 },
  { name: "Cow Me Burger", location: "São Paulo", cuisine: "Delivery", visited: false, rating: 0 },
  { name: "Bia Hoi", location: "São Paulo", cuisine: "Delivery", visited: false, rating: 0 },
  { name: "Good Stuff Burger", location: "São Paulo", cuisine: "Delivery", visited: false, rating: 0 },

  // Já fomos
  { name: "Notorius Fish", location: "Pinheiros, São Paulo", cuisine: "Frutos do Mar", visited: true, rating: 8 },
  { name: "El Mercado Ibérico", location: "São Paulo", cuisine: "Espanhol", visited: true, rating: 8 },
  { name: "Miski", location: "Jardins, São Paulo", cuisine: "Árabe", visited: true, rating: 8 },
  { name: "Muli", location: "São Paulo", cuisine: "Frutos do Mar", visited: true, rating: 7 },
  { name: "Bai 180", location: "São Paulo", cuisine: "Asiático", visited: true, rating: 8 },
  { name: "Ella Fitz", location: "São Paulo", cuisine: "Bar", visited: true, rating: 8 },
  { name: "Aiô", location: "São Paulo", cuisine: "Taiwanês", visited: true, rating: 10 },
  { name: "Lê Bulo", location: "São Paulo", cuisine: "Variado", visited: true, rating: 8 },
  { name: "Trattorita Evvai", location: "São Paulo", cuisine: "Italiano", visited: true, rating: 7.5 },
  { name: "Agello", location: "São Paulo", cuisine: "Italiano", visited: true, rating: 8.5 },
  { name: "Simpatia 105", location: "São Paulo", cuisine: "Frutos do Mar", visited: true, rating: 10 },
  { name: "Broca", location: "Vila Madalena, São Paulo", cuisine: "Variado", visited: true, rating: 9 },
  { name: "Izakaya Otoshi", location: "São Paulo", cuisine: "Japonês", visited: true, rating: 10 },
  { name: "Hira Ramen Izakaya", location: "São Paulo", cuisine: "Japonês", visited: true, rating: 9 },
  { name: "Shigue", location: "São Paulo", cuisine: "Japonês", visited: true, rating: 8.5 },
  { name: "Mapu", location: "Vila Mariana, São Paulo", cuisine: "Taiwanês", visited: true, rating: 8.5 },
  { name: "Petisquinho do Bob", location: "Perdizes, São Paulo", cuisine: "Variado", visited: true, rating: 7.5 },
  { name: "Deli Doner", location: "São Paulo", cuisine: "Variado", visited: true, rating: 8 },
  { name: "Lardo", location: "Pompeia, São Paulo", cuisine: "Variado", visited: true, rating: 9 },
  { name: "Taqueria La Sobrosa", location: "São Paulo", cuisine: "Mexicano", visited: true, rating: 8 },
  { name: "Fogo e Mar", location: "São Paulo", cuisine: "Frutos do Mar", visited: true, rating: 8.5 },
  { name: "Barbatana Amarela", location: "São Paulo", cuisine: "Frutos do Mar", visited: true, rating: 8.5 },
  { name: "Blu Bar", location: "Pinheiros, São Paulo", cuisine: "Bar", visited: true, rating: 7.5 },
  { name: "Pescador Grill", location: "Vila Madalena, São Paulo", cuisine: "Frutos do Mar", visited: true, rating: 9 },
  { name: "Cora", location: "Centro, São Paulo", cuisine: "Variado", visited: true, rating: 9 },
  { name: "Pé pra Fora", location: "São Paulo", cuisine: "Bar", visited: true, rating: 8.5 },
  { name: "Make Hommus Not War", location: "São Paulo", cuisine: "Árabe", visited: true, rating: 8.8 },
  { name: "Santokki", location: "São Paulo", cuisine: "Coreano", visited: true, rating: 8 },
  { name: "Carlos Pizza", location: "São Paulo", cuisine: "Pizzaria", visited: true, rating: 8.5 },
  { name: "Bar Sururu", location: "Barra Funda, São Paulo", cuisine: "Bar", visited: true, rating: 7.5 },
  { name: "Cais", location: "São Paulo", cuisine: "Variado", visited: true, rating: 8.75 },
  { name: "Kinboshi", location: "São Paulo", cuisine: "Japonês", visited: true, rating: 8 },
  { name: "Azur do Mar", location: "Pinheiros, São Paulo", cuisine: "Frutos do Mar", visited: true, rating: 9 },
  { name: "Lobozo", location: "Vila Madalena, São Paulo", cuisine: "Brasileiro", visited: true, rating: 8.5 },
  { name: "Clandestina", location: "São Paulo", cuisine: "Variado", visited: true, rating: 7.5 },
  { name: "Barkatu", location: "São Paulo", cuisine: "Variado", visited: true, rating: 7.5 },
  { name: "Paul's Boutique", location: "Itaim, São Paulo", cuisine: "Pizzaria", visited: true, rating: 0 },
  { name: "Jacó", location: "Vila Madalena, São Paulo", cuisine: "Variado", visited: true, rating: 9 },
  { name: "Kazuo", location: "São Paulo", cuisine: "Japonês", visited: true, rating: 8 },
  { name: "Ping Yang", location: "São Paulo", cuisine: "Asiático", visited: true, rating: 8 },
  { name: "Guru Sushi", location: "Guarujá", cuisine: "Japonês", visited: true, rating: 0 },
  { name: "Komah", location: "São Paulo", cuisine: "Padaria", visited: true, rating: 8 },
  { name: "Brisa do Baru", location: "São Paulo", cuisine: "Variado", visited: true, rating: 8.5 },

  // Bares
  { name: "Koya 88", location: "São Paulo", cuisine: "Bar", visited: false, rating: 0 },
  { name: "Aconchegante", location: "São Paulo", cuisine: "Bar", visited: false, rating: 0 },
  { name: "The Liquor Store", location: "São Paulo", cuisine: "Bar", visited: false, rating: 0 },
  { name: "Bar Balcão", location: "São Paulo", cuisine: "Bar", visited: false, rating: 0 },
  { name: "Cineclube Cortina", location: "São Paulo", cuisine: "Bar", visited: false, rating: 0 },
  { name: "Fel", location: "São Paulo", cuisine: "Bar", visited: false, rating: 0 },
  { name: "The Punch Bar", location: "São Paulo", cuisine: "Bar", visited: false, rating: 0 },
  { name: "Bar dos Cravos", location: "São Paulo", cuisine: "Bar", visited: false, rating: 0 },
  { name: "Bar do Luiz Fernandes", location: "São Paulo", cuisine: "Bar", visited: false, rating: 0 },
  { name: "Domo Bar", location: "São Paulo", cuisine: "Bar", visited: false, rating: 0 },
  { name: "Clementina", location: "São Paulo", cuisine: "Bar de Vinhos", visited: false, rating: 0 },
  { name: "Matiz", location: "São Paulo", cuisine: "Bar", visited: false, rating: 0 },
  { name: "Shiro Cocktail", location: "São Paulo", cuisine: "Bar", visited: false, rating: 0 },
  { name: "Hideout the Door", location: "São Paulo", cuisine: "Bar", visited: false, rating: 0 },
  { name: "Atlântico 212", location: "Pinheiros, São Paulo", cuisine: "Bar", visited: true, rating: 9 },
  { name: "Lita", location: "São Paulo", cuisine: "Bar de Vinhos", visited: false, rating: 0 },
  { name: "Luci Bar", location: "São Paulo", cuisine: "Bar", visited: false, rating: 0 },

  // Sobremesas
  { name: "Marcelo Pudim", location: "São Paulo", cuisine: "Sobremesa", visited: false, rating: 0 },
  { name: "A Casa da Búlgara", location: "São Paulo", cuisine: "Sobremesa", visited: false, rating: 0 },

  // Pelo Mundo
  { name: "Bodega El Capricho", location: "Espanha", cuisine: "Espanhol", visited: false, rating: 0 },
  { name: "Lotte", location: "Coreia do Sul", cuisine: "Coreano", visited: false, rating: 0 },
  { name: "Boia", location: "Salvador, Bahia", cuisine: "Brasileiro", visited: false, rating: 0 },
  { name: "Salt Hanks", location: "Nova York", cuisine: "Lanche", visited: false, rating: 0 },
  { name: "Krispy Pizza", location: "Nova York", cuisine: "Pizzaria", visited: false, rating: 0 },
  { name: "Quel Che C'è Laboratório Di Cucina", location: "Roma", cuisine: "Italiano", visited: false, rating: 0 },
  { name: "Klay By Karak", location: "Dubai", cuisine: "Café", visited: false, rating: 0 },
  { name: "Dorian", location: "Londres", cuisine: "Variado", visited: false, rating: 0 },
];

export default defaults;
